// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: api/javascript.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptRequest) Reset() {
	*x = ScriptRequest{}
	mi := &file_api_javascript_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptRequest) ProtoMessage() {}

func (x *ScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_javascript_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptRequest.ProtoReflect.Descriptor instead.
func (*ScriptRequest) Descriptor() ([]byte, []int) {
	return file_api_javascript_proto_rawDescGZIP(), []int{0}
}

func (x *ScriptRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type ScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultPayload string                 `protobuf:"bytes,1,opt,name=result_payload,json=resultPayload,proto3" json:"result_payload,omitempty"` // JSON serialized result
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptResponse) Reset() {
	*x = ScriptResponse{}
	mi := &file_api_javascript_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptResponse) ProtoMessage() {}

func (x *ScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_javascript_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptResponse.ProtoReflect.Descriptor instead.
func (*ScriptResponse) Descriptor() ([]byte, []int) {
	return file_api_javascript_proto_rawDescGZIP(), []int{1}
}

func (x *ScriptResponse) GetResultPayload() string {
	if x != nil {
		return x.ResultPayload
	}
	return ""
}

func (x *ScriptResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type BindRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ApiName               string                 `protobuf:"bytes,1,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`
	ImplementationPayload string                 `protobuf:"bytes,2,opt,name=implementation_payload,json=implementationPayload,proto3" json:"implementation_payload,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	mi := &file_api_javascript_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_javascript_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_api_javascript_proto_rawDescGZIP(), []int{2}
}

func (x *BindRequest) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *BindRequest) GetImplementationPayload() string {
	if x != nil {
		return x.ImplementationPayload
	}
	return ""
}

type BindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindResponse) Reset() {
	*x = BindResponse{}
	mi := &file_api_javascript_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResponse) ProtoMessage() {}

func (x *BindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_javascript_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResponse.ProtoReflect.Descriptor instead.
func (*BindResponse) Descriptor() ([]byte, []int) {
	return file_api_javascript_proto_rawDescGZIP(), []int{3}
}

func (x *BindResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BindResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_api_javascript_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_javascript_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_api_javascript_proto_rawDescGZIP(), []int{4}
}

func (x *EventRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_api_javascript_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_javascript_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_api_javascript_proto_rawDescGZIP(), []int{5}
}

func (x *EventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EventResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_javascript_proto protoreflect.FileDescriptor

const file_api_javascript_proto_rawDesc = "" +
	"\n" +
	"\x14api/javascript.proto\x12\x03api\"'\n" +
	"\rScriptRequest\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\"\\\n" +
	"\x0eScriptResponse\x12%\n" +
	"\x0eresult_payload\x18\x01 \x01(\tR\rresultPayload\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"_\n" +
	"\vBindRequest\x12\x19\n" +
	"\bapi_name\x18\x01 \x01(\tR\aapiName\x125\n" +
	"\x16implementation_payload\x18\x02 \x01(\tR\x15implementationPayload\"M\n" +
	"\fBindResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"`\n" +
	"\fEventRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"N\n" +
	"\rEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xbb\x01\n" +
	"\x11JavaScriptService\x128\n" +
	"\rExecuteScript\x12\x12.api.ScriptRequest\x1a\x13.api.ScriptResponse\x124\n" +
	"\rBindGlobalAPI\x12\x10.api.BindRequest\x1a\x11.api.BindResponse\x126\n" +
	"\rDispatchEvent\x12\x11.api.EventRequest\x1a\x12.api.EventResponseB%Z#github.com/go-chromium-core/gcc/apib\x06proto3"

var (
	file_api_javascript_proto_rawDescOnce sync.Once
	file_api_javascript_proto_rawDescData []byte
)

func file_api_javascript_proto_rawDescGZIP() []byte {
	file_api_javascript_proto_rawDescOnce.Do(func() {
		file_api_javascript_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_javascript_proto_rawDesc), len(file_api_javascript_proto_rawDesc)))
	})
	return file_api_javascript_proto_rawDescData
}

var file_api_javascript_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_javascript_proto_goTypes = []any{
	(*ScriptRequest)(nil),  // 0: api.ScriptRequest
	(*ScriptResponse)(nil), // 1: api.ScriptResponse
	(*BindRequest)(nil),    // 2: api.BindRequest
	(*BindResponse)(nil),   // 3: api.BindResponse
	(*EventRequest)(nil),   // 4: api.EventRequest
	(*EventResponse)(nil),  // 5: api.EventResponse
}
var file_api_javascript_proto_depIdxs = []int32{
	0, // 0: api.JavaScriptService.ExecuteScript:input_type -> api.ScriptRequest
	2, // 1: api.JavaScriptService.BindGlobalAPI:input_type -> api.BindRequest
	4, // 2: api.JavaScriptService.DispatchEvent:input_type -> api.EventRequest
	1, // 3: api.JavaScriptService.ExecuteScript:output_type -> api.ScriptResponse
	3, // 4: api.JavaScriptService.BindGlobalAPI:output_type -> api.BindResponse
	5, // 5: api.JavaScriptService.DispatchEvent:output_type -> api.EventResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_javascript_proto_init() }
func file_api_javascript_proto_init() {
	if File_api_javascript_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_javascript_proto_rawDesc), len(file_api_javascript_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_javascript_proto_goTypes,
		DependencyIndexes: file_api_javascript_proto_depIdxs,
		MessageInfos:      file_api_javascript_proto_msgTypes,
	}.Build()
	File_api_javascript_proto = out.File
	file_api_javascript_proto_goTypes = nil
	file_api_javascript_proto_depIdxs = nil
}
