// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: api/javascript.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	JavaScriptService_ExecuteScript_FullMethodName = "/api.JavaScriptService/ExecuteScript"
	JavaScriptService_BindGlobalAPI_FullMethodName = "/api.JavaScriptService/BindGlobalAPI"
	JavaScriptService_DispatchEvent_FullMethodName = "/api.JavaScriptService/DispatchEvent"
)

// JavaScriptServiceClient is the client API for JavaScriptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JavaScriptServiceClient interface {
	ExecuteScript(ctx context.Context, in *ScriptRequest, opts ...grpc.CallOption) (*ScriptResponse, error)
	BindGlobalAPI(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error)
	DispatchEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
}

type javaScriptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJavaScriptServiceClient(cc grpc.ClientConnInterface) JavaScriptServiceClient {
	return &javaScriptServiceClient{cc}
}

func (c *javaScriptServiceClient) ExecuteScript(ctx context.Context, in *ScriptRequest, opts ...grpc.CallOption) (*ScriptResponse, error) {
	out := new(ScriptResponse)
	err := c.cc.Invoke(ctx, JavaScriptService_ExecuteScript_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *javaScriptServiceClient) BindGlobalAPI(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error) {
	out := new(BindResponse)
	err := c.cc.Invoke(ctx, JavaScriptService_BindGlobalAPI_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *javaScriptServiceClient) DispatchEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, JavaScriptService_DispatchEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JavaScriptServiceServer is the server API for JavaScriptService service.
// All implementations must embed UnimplementedJavaScriptServiceServer
// for forward compatibility
type JavaScriptServiceServer interface {
	ExecuteScript(context.Context, *ScriptRequest) (*ScriptResponse, error)
	BindGlobalAPI(context.Context, *BindRequest) (*BindResponse, error)
	DispatchEvent(context.Context, *EventRequest) (*EventResponse, error)
	mustEmbedUnimplementedJavaScriptServiceServer()
}

// UnimplementedJavaScriptServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJavaScriptServiceServer struct {
}

func (UnimplementedJavaScriptServiceServer) ExecuteScript(context.Context, *ScriptRequest) (*ScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteScript not implemented")
}
func (UnimplementedJavaScriptServiceServer) BindGlobalAPI(context.Context, *BindRequest) (*BindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindGlobalAPI not implemented")
}
func (UnimplementedJavaScriptServiceServer) DispatchEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispatchEvent not implemented")
}
func (UnimplementedJavaScriptServiceServer) mustEmbedUnimplementedJavaScriptServiceServer() {}

// UnsafeJavaScriptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JavaScriptServiceServer will
// result in compilation errors.
type UnsafeJavaScriptServiceServer interface {
	mustEmbedUnimplementedJavaScriptServiceServer()
}

func RegisterJavaScriptServiceServer(s grpc.ServiceRegistrar, srv JavaScriptServiceServer) {
	s.RegisterService(&JavaScriptService_ServiceDesc, srv)
}

func _JavaScriptService_ExecuteScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JavaScriptServiceServer).ExecuteScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JavaScriptService_ExecuteScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JavaScriptServiceServer).ExecuteScript(ctx, req.(*ScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JavaScriptService_BindGlobalAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JavaScriptServiceServer).BindGlobalAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JavaScriptService_BindGlobalAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JavaScriptServiceServer).BindGlobalAPI(ctx, req.(*BindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JavaScriptService_DispatchEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JavaScriptServiceServer).DispatchEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JavaScriptService_DispatchEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JavaScriptServiceServer).DispatchEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JavaScriptService_ServiceDesc is the grpc.ServiceDesc for JavaScriptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JavaScriptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.JavaScriptService",
	HandlerType: (*JavaScriptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteScript",
			Handler:    _JavaScriptService_ExecuteScript_Handler,
		},
		{
			MethodName: "BindGlobalAPI",
			Handler:    _JavaScriptService_BindGlobalAPI_Handler,
		},
		{
			MethodName: "DispatchEvent",
			Handler:    _JavaScriptService_DispatchEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/javascript.proto",
}
