// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: api/parser.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ParserService_ParseHTML_FullMethodName = "/api.ParserService/ParseHTML"
	ParserService_ParseCSS_FullMethodName  = "/api.ParserService/ParseCSS"
)

// ParserServiceClient is the client API for ParserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParserServiceClient interface {
	ParseHTML(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseHTMLResponse, error)
	ParseCSS(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseCSSResponse, error)
}

type parserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParserServiceClient(cc grpc.ClientConnInterface) ParserServiceClient {
	return &parserServiceClient{cc}
}

func (c *parserServiceClient) ParseHTML(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseHTMLResponse, error) {
	out := new(ParseHTMLResponse)
	err := c.cc.Invoke(ctx, ParserService_ParseHTML_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parserServiceClient) ParseCSS(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseCSSResponse, error) {
	out := new(ParseCSSResponse)
	err := c.cc.Invoke(ctx, ParserService_ParseCSS_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParserServiceServer is the server API for ParserService service.
// All implementations must embed UnimplementedParserServiceServer
// for forward compatibility
type ParserServiceServer interface {
	ParseHTML(context.Context, *ParseRequest) (*ParseHTMLResponse, error)
	ParseCSS(context.Context, *ParseRequest) (*ParseCSSResponse, error)
	mustEmbedUnimplementedParserServiceServer()
}

// UnimplementedParserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedParserServiceServer struct {
}

func (UnimplementedParserServiceServer) ParseHTML(context.Context, *ParseRequest) (*ParseHTMLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseHTML not implemented")
}
func (UnimplementedParserServiceServer) ParseCSS(context.Context, *ParseRequest) (*ParseCSSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseCSS not implemented")
}
func (UnimplementedParserServiceServer) mustEmbedUnimplementedParserServiceServer() {}

// UnsafeParserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParserServiceServer will
// result in compilation errors.
type UnsafeParserServiceServer interface {
	mustEmbedUnimplementedParserServiceServer()
}

func RegisterParserServiceServer(s grpc.ServiceRegistrar, srv ParserServiceServer) {
	s.RegisterService(&ParserService_ServiceDesc, srv)
}

func _ParserService_ParseHTML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserServiceServer).ParseHTML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParserService_ParseHTML_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserServiceServer).ParseHTML(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParserService_ParseCSS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserServiceServer).ParseCSS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParserService_ParseCSS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserServiceServer).ParseCSS(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParserService_ServiceDesc is the grpc.ServiceDesc for ParserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ParserService",
	HandlerType: (*ParserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseHTML",
			Handler:    _ParserService_ParseHTML_Handler,
		},
		{
			MethodName: "ParseCSS",
			Handler:    _ParserService_ParseCSS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/parser.proto",
}
