// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: api/parser.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_api_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_api_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ParseHTMLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomPayload    string                 `protobuf:"bytes,1,opt,name=dom_payload,json=domPayload,proto3" json:"dom_payload,omitempty"` // JSON serialized DOMTree
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Resources     []string               `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseHTMLResponse) Reset() {
	*x = ParseHTMLResponse{}
	mi := &file_api_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseHTMLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseHTMLResponse) ProtoMessage() {}

func (x *ParseHTMLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseHTMLResponse.ProtoReflect.Descriptor instead.
func (*ParseHTMLResponse) Descriptor() ([]byte, []int) {
	return file_api_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ParseHTMLResponse) GetDomPayload() string {
	if x != nil {
		return x.DomPayload
	}
	return ""
}

func (x *ParseHTMLResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ParseHTMLResponse) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ParseCSSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CssomPayload  string                 `protobuf:"bytes,1,opt,name=cssom_payload,json=cssomPayload,proto3" json:"cssom_payload,omitempty"` // JSON serialized CSSOMTree
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Resources     []string               `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseCSSResponse) Reset() {
	*x = ParseCSSResponse{}
	mi := &file_api_parser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseCSSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseCSSResponse) ProtoMessage() {}

func (x *ParseCSSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_parser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseCSSResponse.ProtoReflect.Descriptor instead.
func (*ParseCSSResponse) Descriptor() ([]byte, []int) {
	return file_api_parser_proto_rawDescGZIP(), []int{2}
}

func (x *ParseCSSResponse) GetCssomPayload() string {
	if x != nil {
		return x.CssomPayload
	}
	return ""
}

func (x *ParseCSSResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ParseCSSResponse) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_api_parser_proto protoreflect.FileDescriptor

const file_api_parser_proto_rawDesc = "" +
	"\n" +
	"\x10api/parser.proto\x12\x03api\"(\n" +
	"\fParseRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"w\n" +
	"\x11ParseHTMLResponse\x12\x1f\n" +
	"\vdom_payload\x18\x01 \x01(\tR\n" +
	"domPayload\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\tresources\x18\x03 \x03(\tR\tresources\"z\n" +
	"\x10ParseCSSResponse\x12#\n" +
	"\rcssom_payload\x18\x01 \x01(\tR\fcssomPayload\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\tresources\x18\x03 \x03(\tR\tresources2}\n" +
	"\rParserService\x126\n" +
	"\tParseHTML\x12\x11.api.ParseRequest\x1a\x16.api.ParseHTMLResponse\x124\n" +
	"\bParseCSS\x12\x11.api.ParseRequest\x1a\x15.api.ParseCSSResponseB%Z#github.com/go-chromium-core/gcc/apib\x06proto3"

var (
	file_api_parser_proto_rawDescOnce sync.Once
	file_api_parser_proto_rawDescData []byte
)

func file_api_parser_proto_rawDescGZIP() []byte {
	file_api_parser_proto_rawDescOnce.Do(func() {
		file_api_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_parser_proto_rawDesc), len(file_api_parser_proto_rawDesc)))
	})
	return file_api_parser_proto_rawDescData
}

var file_api_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_parser_proto_goTypes = []any{
	(*ParseRequest)(nil),      // 0: api.ParseRequest
	(*ParseHTMLResponse)(nil), // 1: api.ParseHTMLResponse
	(*ParseCSSResponse)(nil),  // 2: api.ParseCSSResponse
}
var file_api_parser_proto_depIdxs = []int32{
	0, // 0: api.ParserService.ParseHTML:input_type -> api.ParseRequest
	0, // 1: api.ParserService.ParseCSS:input_type -> api.ParseRequest
	1, // 2: api.ParserService.ParseHTML:output_type -> api.ParseHTMLResponse
	2, // 3: api.ParserService.ParseCSS:output_type -> api.ParseCSSResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_parser_proto_init() }
func file_api_parser_proto_init() {
	if File_api_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_parser_proto_rawDesc), len(file_api_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_parser_proto_goTypes,
		DependencyIndexes: file_api_parser_proto_depIdxs,
		MessageInfos:      file_api_parser_proto_msgTypes,
	}.Build()
	File_api_parser_proto = out.File
	file_api_parser_proto_goTypes = nil
	file_api_parser_proto_depIdxs = nil
}
