// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: api/renderer.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RendererService_ComputeLayout_FullMethodName = "/api.RendererService/ComputeLayout"
	RendererService_PaintLayout_FullMethodName   = "/api.RendererService/PaintLayout"
)

// RendererServiceClient is the client API for RendererService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RendererServiceClient interface {
	ComputeLayout(ctx context.Context, in *LayoutRequest, opts ...grpc.CallOption) (*LayoutResponse, error)
	PaintLayout(ctx context.Context, in *PaintRequest, opts ...grpc.CallOption) (*PaintResponse, error)
}

type rendererServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRendererServiceClient(cc grpc.ClientConnInterface) RendererServiceClient {
	return &rendererServiceClient{cc}
}

func (c *rendererServiceClient) ComputeLayout(ctx context.Context, in *LayoutRequest, opts ...grpc.CallOption) (*LayoutResponse, error) {
	out := new(LayoutResponse)
	err := c.cc.Invoke(ctx, RendererService_ComputeLayout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendererServiceClient) PaintLayout(ctx context.Context, in *PaintRequest, opts ...grpc.CallOption) (*PaintResponse, error) {
	out := new(PaintResponse)
	err := c.cc.Invoke(ctx, RendererService_PaintLayout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RendererServiceServer is the server API for RendererService service.
// All implementations must embed UnimplementedRendererServiceServer
// for forward compatibility
type RendererServiceServer interface {
	ComputeLayout(context.Context, *LayoutRequest) (*LayoutResponse, error)
	PaintLayout(context.Context, *PaintRequest) (*PaintResponse, error)
	mustEmbedUnimplementedRendererServiceServer()
}

// UnimplementedRendererServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRendererServiceServer struct {
}

func (UnimplementedRendererServiceServer) ComputeLayout(context.Context, *LayoutRequest) (*LayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeLayout not implemented")
}
func (UnimplementedRendererServiceServer) PaintLayout(context.Context, *PaintRequest) (*PaintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaintLayout not implemented")
}
func (UnimplementedRendererServiceServer) mustEmbedUnimplementedRendererServiceServer() {}

// UnsafeRendererServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RendererServiceServer will
// result in compilation errors.
type UnsafeRendererServiceServer interface {
	mustEmbedUnimplementedRendererServiceServer()
}

func RegisterRendererServiceServer(s grpc.ServiceRegistrar, srv RendererServiceServer) {
	s.RegisterService(&RendererService_ServiceDesc, srv)
}

func _RendererService_ComputeLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendererServiceServer).ComputeLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RendererService_ComputeLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendererServiceServer).ComputeLayout(ctx, req.(*LayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RendererService_PaintLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendererServiceServer).PaintLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RendererService_PaintLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendererServiceServer).PaintLayout(ctx, req.(*PaintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RendererService_ServiceDesc is the grpc.ServiceDesc for RendererService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RendererService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.RendererService",
	HandlerType: (*RendererServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeLayout",
			Handler:    _RendererService_ComputeLayout_Handler,
		},
		{
			MethodName: "PaintLayout",
			Handler:    _RendererService_PaintLayout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/renderer.proto",
}
