// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: api/renderer.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomPayload    string                 `protobuf:"bytes,1,opt,name=dom_payload,json=domPayload,proto3" json:"dom_payload,omitempty"` // JSON serialized DOM for IPC
	CssPayload    string                 `protobuf:"bytes,2,opt,name=css_payload,json=cssPayload,proto3" json:"css_payload,omitempty"` // JSON serialized CSSOM for IPC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayoutRequest) Reset() {
	*x = LayoutRequest{}
	mi := &file_api_renderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutRequest) ProtoMessage() {}

func (x *LayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_renderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutRequest.ProtoReflect.Descriptor instead.
func (*LayoutRequest) Descriptor() ([]byte, []int) {
	return file_api_renderer_proto_rawDescGZIP(), []int{0}
}

func (x *LayoutRequest) GetDomPayload() string {
	if x != nil {
		return x.DomPayload
	}
	return ""
}

func (x *LayoutRequest) GetCssPayload() string {
	if x != nil {
		return x.CssPayload
	}
	return ""
}

type LayoutResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LayoutTreePayload string                 `protobuf:"bytes,1,opt,name=layout_tree_payload,json=layoutTreePayload,proto3" json:"layout_tree_payload,omitempty"` // JSON serialized LayoutTree
	ErrorMessage      string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LayoutResponse) Reset() {
	*x = LayoutResponse{}
	mi := &file_api_renderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutResponse) ProtoMessage() {}

func (x *LayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_renderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutResponse.ProtoReflect.Descriptor instead.
func (*LayoutResponse) Descriptor() ([]byte, []int) {
	return file_api_renderer_proto_rawDescGZIP(), []int{1}
}

func (x *LayoutResponse) GetLayoutTreePayload() string {
	if x != nil {
		return x.LayoutTreePayload
	}
	return ""
}

func (x *LayoutResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PaintRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LayoutTreePayload string                 `protobuf:"bytes,1,opt,name=layout_tree_payload,json=layoutTreePayload,proto3" json:"layout_tree_payload,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaintRequest) Reset() {
	*x = PaintRequest{}
	mi := &file_api_renderer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaintRequest) ProtoMessage() {}

func (x *PaintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_renderer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaintRequest.ProtoReflect.Descriptor instead.
func (*PaintRequest) Descriptor() ([]byte, []int) {
	return file_api_renderer_proto_rawDescGZIP(), []int{2}
}

func (x *PaintRequest) GetLayoutTreePayload() string {
	if x != nil {
		return x.LayoutTreePayload
	}
	return ""
}

type PaintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaintResponse) Reset() {
	*x = PaintResponse{}
	mi := &file_api_renderer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaintResponse) ProtoMessage() {}

func (x *PaintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_renderer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaintResponse.ProtoReflect.Descriptor instead.
func (*PaintResponse) Descriptor() ([]byte, []int) {
	return file_api_renderer_proto_rawDescGZIP(), []int{3}
}

func (x *PaintResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaintResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_renderer_proto protoreflect.FileDescriptor

const file_api_renderer_proto_rawDesc = "" +
	"\n" +
	"\x12api/renderer.proto\x12\x03api\"Q\n" +
	"\rLayoutRequest\x12\x1f\n" +
	"\vdom_payload\x18\x01 \x01(\tR\n" +
	"domPayload\x12\x1f\n" +
	"\vcss_payload\x18\x02 \x01(\tR\n" +
	"cssPayload\"e\n" +
	"\x0eLayoutResponse\x12.\n" +
	"\x13layout_tree_payload\x18\x01 \x01(\tR\x11layoutTreePayload\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\">\n" +
	"\fPaintRequest\x12.\n" +
	"\x13layout_tree_payload\x18\x01 \x01(\tR\x11layoutTreePayload\"N\n" +
	"\rPaintResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\x81\x01\n" +
	"\x0fRendererService\x128\n" +
	"\rComputeLayout\x12\x12.api.LayoutRequest\x1a\x13.api.LayoutResponse\x124\n" +
	"\vPaintLayout\x12\x11.api.PaintRequest\x1a\x12.api.PaintResponseB%Z#github.com/go-chromium-core/gcc/apib\x06proto3"

var (
	file_api_renderer_proto_rawDescOnce sync.Once
	file_api_renderer_proto_rawDescData []byte
)

func file_api_renderer_proto_rawDescGZIP() []byte {
	file_api_renderer_proto_rawDescOnce.Do(func() {
		file_api_renderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_renderer_proto_rawDesc), len(file_api_renderer_proto_rawDesc)))
	})
	return file_api_renderer_proto_rawDescData
}

var file_api_renderer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_renderer_proto_goTypes = []any{
	(*LayoutRequest)(nil),  // 0: api.LayoutRequest
	(*LayoutResponse)(nil), // 1: api.LayoutResponse
	(*PaintRequest)(nil),   // 2: api.PaintRequest
	(*PaintResponse)(nil),  // 3: api.PaintResponse
}
var file_api_renderer_proto_depIdxs = []int32{
	0, // 0: api.RendererService.ComputeLayout:input_type -> api.LayoutRequest
	2, // 1: api.RendererService.PaintLayout:input_type -> api.PaintRequest
	1, // 2: api.RendererService.ComputeLayout:output_type -> api.LayoutResponse
	3, // 3: api.RendererService.PaintLayout:output_type -> api.PaintResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_renderer_proto_init() }
func file_api_renderer_proto_init() {
	if File_api_renderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_renderer_proto_rawDesc), len(file_api_renderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_renderer_proto_goTypes,
		DependencyIndexes: file_api_renderer_proto_depIdxs,
		MessageInfos:      file_api_renderer_proto_msgTypes,
	}.Build()
	File_api_renderer_proto = out.File
	file_api_renderer_proto_goTypes = nil
	file_api_renderer_proto_depIdxs = nil
}
